name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Install ADB
        run: sudo apt-get install -y adb
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml
      - name: Install APK
        run: |
          device_id=$(adb devices | awk 'FNR == 2 {print $1}')
          apk_file_path="/Users/stefan/Desktop/ContainerAndroidAutomation/AC.apk"
          package_name=$(aapt dump badging "$apk_file_path" | awk -v FS="'" '/package: name=/{print $2}')
          if [[ $(adb -s $device_id shell pm list packages $package_name) ]]; then
            echo "APK is already installed on device"
          else
            adb -s $device_id install "$apk_file_path"
          fi


  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: ${{ secrets.JAVA_HOME }}
      ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
      ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
      PATH: /Users/stefan/Desktop/ContainerAndroidAutomation/AC-0417.apk:/usr/local/openjdk-11/bin:/usr/local/android-sdk/tools:/usr/local/android-sdk/platform-tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install ADB
        run: sudo apt-get install -y adb
      - name: Connect to Android device
        run: |
          adb devices
          adb -s 08301JEC200526 wait-for-device
          adb -s 08301JEC200526 shell input keyevent 82 &
        env:
          YOUR_DEVICE_SERIAL: 08301JEC200526
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium -p ${{ env.APPIUM_PORT }} &
        env:
          APPIUM_PORT: 4723
      - name: Wait for Appium to start
        run: |
          timeout 60s bash -c 'until echo > /dev/tcp/127.0.0.1/$APPIUM_PORT; do sleep 1; done'
      - name: Run Appium tests
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
