name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_APP_NAME: "Bstack-[Java] Sample Test"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Android environment
        run: echo "export ANDROID_HOME=/Users/stefan/Library/Android/sdk" >> $GITHUB_ENV
      - name: Install ADB
        run: brew install --cask android-platform-tools
      - name: Update PATH environment variable
        run: echo 'export PATH="$PATH:/usr/local/share/android-sdk/platform-tools"' >> $GITHUB_ENV
      - name: Check and install coreutils
        run: |
          if ! command -v timeout &> /dev/null; then
            brew install coreutils
          fi
      - name: Install Appium
        run: npm install -g appium
      - name: Start Appium server
        run: appium &
      - name: Wait for Appium to start
        run: |
         timeout 60s bash -c 'until [[ $(lsof -t -i :4723) ]]; do sleep 1; done'
      - name: Install app dependencies
        run: npm install
      - name: Run Appium tests on BrowserStack
        id: browserstack
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test -P browserstack --file pom.xml
      - name: Print BrowserStack job ID
        run: echo "BrowserStack job ID:${{ steps.browserstack.outputs.job_id }}"
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
