name: Java Appium Automation CI
on:
  push:
    branches: [ main ]

jobs:
  appium:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /users/stefan/Library/Android/sdk
      JAVA_HOME: /usr/libexec/java_home
      PATH: $ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
    


    steps:
      - name: Install tar
        run: apt-get install -y tar # For Ubuntu

      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Run Appium tests
        run: npm run appium-test

  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Appium
        run: npm install -g appium
      - name: Start Appium Server
        run: appium &
      - name: Run Appium Test
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
         name: Test Report
         path: Extent-Report/Report

