name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Install ADB
        run: sudo apt-get install -y adb
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml
      - name: Install APK
        run: |
          sudo adb devices
          adb -s 08301JEC200526	 wait-for-device
          adb -s 08301JEC200526	 install -r ${{ github.workspace }}/AC.apk

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/libexec/java_home
      ANDROID_HOME: /users/stefan/Library/Android/sdk
      ANDROID_SDK_ROOT: /Library/Android/sdk
      PATH: ${{ github.workspace }}:/usr/libexec/java_home:/users/stefan/Library/Android/sdk/tools:/users/stefan/Library/Android/sdk/platform-tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install ADB
        run: sudo apt-get install -y adb
      - name: Connect to Android device
        run: |
          sudo adb devices
          adb -s 08301JEC200526	 wait-for-device
          adb -s 08301JEC200526	 shell input keyevent 82 &
        env:
          YOUR_DEVICE_SERIAL: 08301JEC200526	
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium -p ${{ env.APPIUM_PORT }} &
        env:
          APPIUM_PORT: 4723
      - name: Wait for Appium to start
        run: |
          timeout 60s bash -c 'until echo > /dev/tcp/127.0.0.1/$APPIUM_PORT; do sleep 1; done'
      - name: Run Appium tests
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
