name: Java Appium Automation CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file /AC_Android_BDD/pom.xml
      - name: List files in directory
        run: ls -R


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Appium
        run: npm install -g appium
      - name: Start Appium Server
        run: appium &
      - name: Run Appium Test
        run: mvn -B package --file /ContainerAndroidAutomation/AC_Android_BDD/pom.xml
