name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml

  test:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Android environment
        run: echo "export ANDROID_HOME=/Users/stefan/Library/Android/sdk" >> $GITHUB_ENV
      - name: Install ADB
        run: brew install --cask android-platform-tools
      - name: Update PATH environment variable
        run: echo 'export PATH="$PATH:/usr/local/share/android-sdk/platform-tools"' >> $GITHUB_ENV
      - name: Connect to Android device
        run: |
          adb start-server
          sleep 5
          adb devices
          adb -s ${{ secrets.ANDROID_SERIAL }} wait-for-device
          adb -s ${{ secrets.ANDROID_SERIAL }} shell input keyevent 82 &
        env:
          ANDROID_SERIAL: ${{ secrets.ANDROID_SERIAL }}
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium &
      - name: Wait for Appium to start
        run: |
         timeout 60s bash -c 'until [[ $(lsof -t -i :4723) ]]; do sleep 1; done'
      - name: Install APK
        run: adb -s ${{ secrets.ANDROID_SERIAL }} install -r AC.apk
      - name: Run Appium tests
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
