name: Appium Android Automation

on:
  push:
    branches: [main]

jobs:
  appium-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: "android-30"
          ndk-version: "21.4.7075529"
          java-version: 11.0.11
      - name: Install dependencies
        run: mvn dependency:resolve
      - name: Run Appium tests
        run: mvn test -Dtest=TestSuite
