name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml

  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Connect to BrowserStack
        uses: browserstack/github-actions@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-Key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium &
      - name: Wait for Appium to start
        run: |
          brew install coreutils
          gtimeout 60s bash -c 'until [[ $(lsof -t -i :4723) ]]; do sleep 1; done'
      - name: Upload app to BrowserStack
        run: curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }} -X POST https://api-cloud.browserstack.com/app-automate/upload -F file=@AC.apk
      - name: Run Appium tests
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
