name: Java Appium Automation CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls
      - name: Install ADB
        run: |
          curl -O "https://dl.google.com/android/repository/platform-tools-latest-darwin.zip"
          unzip platform-tools-latest-darwin.zip -d $HOME/Library/Android/sdk/
          echo $PATH
          echo $ANDROID_HOME
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml
      - name: Install APK
        run: adb -s 08301JEC200526 install -r ${{ github.workspace }}/AC.apk

  test:
    needs: build
    runs-on: macos-latest
    env:
      JAVA_HOME: ${{ matrix.java-version }}
      ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
      ANDROID_SDK_ROOT: $HOME/Library/Android/sdk
      PATH: ${{ env.PATH }}:${{ env.ANDROID_HOME }}/platform-tools:${{ env.ANDROID_HOME }}/emulator:${{ env.ANDROID_HOME }}/tools:${{ env.ANDROID_HOME }}/tools/bin
    strategy:
      matrix:
        java-version: [11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install ADB
        run: |
          curl -O "https://dl.google.com/android/repository/platform-tools-latest-darwin.zip"
          unzip platform-tools-latest-darwin.zip -d $HOME/Library/Android/sdk/
          echo $PATH
          echo $ANDROID_HOME
      - name: Connect to Android device
        run: |
          adb devices
          adb -s 08301JEC200526 wait-for-device
          adb -s 08301JEC200526 shell input keyevent 82 &
        env:
          YOUR_DEVICE_SERIAL: 08301JEC200526
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium -p ${{ env.APPIUM_PORT }} &
        env:
          APPIUM_PORT: 4723
      - name: Wait for Appium to start
        run: |
          timeout 60s bash -c 'until echo > /dev/tcp/127.0.0.1/$APPIUM_PORT; do sleep 1; done'
      - name: Run Appium tests
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
