name: Appium Tests on BrowserStack

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up BrowserStack environment
        run: |
          echo "BROWSERSTACK_USERNAME=answerconnect_d0BTEv" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=wjqrx6hhPmJcz2k7BH3T" >> $GITHUB_ENV
          echo "BROWSERSTACK_APP=bs://9e835a485b0a05ee7e844cdd7d1b565762a5c792" >> $GITHUB_ENV
          echo "BROWSERSTACK_DEVICE=Google Pixel 6 Pro" >> $GITHUB_ENV
          echo "BROWSERSTACK_OS=13.0" >> $GITHUB_ENV
      - name: Install app dependencies
        run: |
          npm install -g appium
          npm install
      - name: Start Appium server
        run: appium &
      - name: Wait for Appium to start
        run: |
         timeout 60s bash -c 'until [[ $(lsof -t -i :4723) ]]; do sleep 1; done'
      - name: 'Running test on BrowserStack'
        run: node /usr/local/lib/node_modules/npm/index.js
     # - name: Run Appium tests on BrowserStack
      #  run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 test -P browserstack --file pom.xml
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Extent-Report/Report/
