name: Java Appium Automation CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check if pom.xml exists
        run: ls -la
      - name: Build with Maven
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install ADB
        run: sudo apt-get install -y adb
      - name: Connect to Android device
        run: adb devices
        env:
          ANDROID_SERIAL: 192.168.1.3:5555
      - name: Install APK file on device
        run: adb install /Users/stefan/Desktop/ContainerAndroidAutomation/src/main/resources/AC.apk
      - name: Install Appium
        run: npm install -g appium
      - name: Start Appium Server
        run: appium &
      - name: Run Appium Test
        run: mvn -B -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 package --file pom.xml
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: Extent-Report/Report
