name: Android Automation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: android-actions/setup-android-sdk@v2
        with:
          components: tools
      - name: Build and test with Maven
        run: |
          mvn clean install -DskipTests=false
        env:
          APPIUM_URL: http://localhost:4723/wd/hub
          DEVICE_NAME: 08301JEC200526
          PLATFORM_VERSION: 13
